# ─────────────────────────────────────────
# SERVICE — BACKEND
# ClusterIP — ingress controller routes to it
# ─────────────────────────────────────────
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: three-tier
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000